/*
 * MotorDC.h
 *
 *  Created on: Oct 26, 2019
 *      Author: Sprints
 */

#ifndef DCMOTOR_H_
#define DCMOTOR_H_
#include "dcMotorConfig.h"
#include "timers.h"

typedef enum En_motorType_t{
	MOT_1,
	MOT_2
}En_motorType_t;

typedef enum En_motorDir_t{
	STOP,
	FORWARD,
	BACKWARD
}En_motorDir_t;

/**
 * Description: Initializes motor pins as output
 * @param motor number
 */
void MotorDC_Init(En_motorType_t en_motor_number);

/**
 * Description: Sets the direction behavior of the motor
 * @param motor number
 * @param direction behavior
 */
void MotorDC_Dir(En_motorType_t en_motor_number, En_motorDir_t en_motor_dir);

/**
 * Description: Control motors speed by SW PWM signal generated by timer0
 * @param motor speed as duty cycle
 */
void MotorDC_Speed_PollingWithT0(uint8_t u8_motor_speed);

/**
 * Description: Control motors speed by HW PWM signal generated by timer1 
 * @param motor speed as duty cycle
 */
void MotorDC_Speed_HwPWM(uint8_t u8_motor_speed);

#endif /* MOTORDC_H_ */